### ISSUE TITLE
loadScript: Script continues to load after onerror

### ISSUE THREAD

**Issue by mintyfloss** [bazaarvoice/scoutfile#8]
When using `loadScript`, I noticed that if my script takes longer than the default 1 sec, the script will continue to load and execute. Is this by design? In this scenario, `onerror` still gets called and eventually `cleanup` gets called too.

This happens in all browsers except for IE8 which relies on the `script.onclick();` trick, which never gets called because `onreadystatechange` gets removed during `cleanup`.

**Comment by rmurphey** [comment]
Can you provide a test case/steps to reproduce?

**Comment by mintyfloss** [comment]
I created a repo to demo this issue. https://github.com/mintyfloss/loadscriptTest

**Comment by lawnsea** [comment]
This is "by design" in that it's how `script` tags work. Once the tag is injected, the browser will attempt to download the script and evaluate it. The timeout has no effect on this process, which cannot be canceled.

Some browsers do not fire `error` when a script times out or 404s. The timeout is a way for the application to set an amount of time after which it will assume the download has failed. Your application will need to set an appropriate timeout and fail cleanly in the case that it expires.

**Comment by lawnsea** [comment]
I opened #9 to consider whether the default timeout should be increased.

I'm surprised by the IE8 behavior. I would expect the script to be evaluated but the callback not invoked. I've opened #10 to track this.
